server:
  port: 8080

  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.thoughtmechanix: DEBUG
    config: "classpath:logback-spring.xml"

zuul:
  routes:
    organizationservice:
      url: http://organization:8080
      #url: http://localhost:8081
  ratelimit:
    key-prefix: your-prefix
    enabled: true
    repository: REDIS
    behind-proxy: true
    default-policy: #optional - will apply unless specific policy exists
      limit: 5 #optional - request number limit per refresh interval window
      quota: 1000 #optional - request time limit per refresh interval window (in seconds)
      refresh-interval: 60 #default value (in seconds)
      type: #optional
        - user
        #- origin
        - url
    policies:
      myServiceId:
        limit: 10 #optional - request number limit per refresh interval window
        quota: 1000 #optional - request time limit per refresh interval window (in seconds)
        refresh-interval: 600 #default value (in seconds)
        type: #optional
          - user
          #- origin
          - url

redis:
  host: redis://redis
  port: 6379
  password: mXLQREUpidyGiVlc
